syntax on
colorscheme koehler
let g:molokai_origin = 1
let g:rehash256 = 1
set t_Co=256
set noswapfile
set number

"ステータス表示
set laststatus=2
set statusline=%F%r%=%h

set incsearch
set list
set listchars=tab:^\ ,trail:~
set guifont=meiryo:h16:cSHIFTJIS
set encoding=utf-8
set fenc=utf-8
set fileformats=unix,dos,mac
