. ~/dotfiles/sh/common/init.sh

# vcs_infoロード
autoload -Uz vcs_info
# PROMPT変数内で変数参照する
setopt prompt_subst

# vcsの表示
zstyle ':vcs_info:*' formats '[%F{blue}%b%f]'
zstyle ':vcs_info:*' actionformats '[%F{blue}%b%f(%F{red}%a%f)]'
# プロンプト表示直前にvcs_info呼び出し
precmd() { vcs_info }
# プロンプト表示
RPROMPT='${vcs_info_msg_0_}'


PROMPT='%F{green}%n@%m%f %F{yellow}%~%f
%# '

# completion
autoload -U compinit
compinit

# color
autoload -U colors
colors

#allow tab completion in the middle of a word
setopt COMPLETE_IN_WORD

## keep background processes at full speed
#setopt NOBGNICE
## restart running processes on exit
#setopt HUP

# history
setopt APPEND_HISTORY
# for sharing history between zsh processes
setopt INC_APPEND_HISTORY
setopt SHARE_HISTORY

# never ever beep ever
setopt NO_BEEP

# automatically decide when to page a list of completions
LISTMAX=0

# disable mail checking
MAILCHECK=0
