# .bashrc

#env variables
export PAGER=less


#invalid ctr+s and ctr+q
stty -ixon -ixoff

#git complete
source ~/dotfiles/bash/git-prompt.sh

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

#prompt
GIT_PS1_SHOWDIRTYSTATE=true

RIGHT='\[\e[$[COLUMNS-$(echo -n " $(__git_ps1)" | wc -c)]C\[\e[0;36m\]$(__git_ps1)\e[\e[$[COLUMNS]D\]'
MAIN='\[\e[1;32m\]\u[\w]'
L2="\[\e[1;37m\]\$?\$"
PS1="${RIGHT}${MAIN}\n${L2} "
# User specific aliases and functions

#super user
alias _="sudo"

#list directory
alias ls='ls -G'        # Compact view, show colors
alias la='ls -AF'       # Compact view, show hidden
alias ll='ls -al'
alias l='ls -a'
alias l1='ls -1'

#change directory
alias ..='cd ..'         # Go up one directory
alias ...='cd ../..'     # Go up two directories
alias ....='cd ../../..' # Go up three directories

# Directory
alias md='mkdir -p'
alias rd='rmdir'

#other aliases
alias t='date'
alias c='clear'
alias q='exit'
alias h='history'
alias s='source'

#git aliases
alias g='git'
alias gs='git status'
alias ga='git add'
alias gco='git checkout'
alias gc='git commit'
alias gcm='git commit -m'
alias gl='git log'
alias gsh='git show'
alias gd='git diff '
alias gdc='git diff --cached'
alias gb='git branch'
alias gmv='git mv'
alias grm='git rm'
alias grmc='git rm --cached'
alias gre='git reset'

#edit alias
alias bashrc='vim ~/.bashrc'
alias vimrc='vim ~/.vimrc'
